### ISSUE TITLE
Can it work in Windows 10?

### ISSUE THREAD

**Issue by EdXian** [rxdu/apriltag_localization#1]
Hi ,
Can I build this package in windows 10?
Thanks in advance!

**Comment by rxdu** [comment]
It should work in Windows but I never tried that.

**Comment by EdXian** [comment]
Thanks, i'll try it.

**Comment by EdXian** [comment]
Hi @rxdu , 
Noticing that if you want to use it with opencv3.3.1 or greater version ,You have to modify the code which is in   `TagDetection.cc`.
Try to change the following snippet
```
cv::Matx33f cameraMatrix(
                                         fx, 0, px,
                                          0, fy, py,
                                         0,  0,  1);

```
to
```
 cv::Matx33d cameraMatrix(
                                          fx, 0, px,
                                           0, fy, py,
                                           0,  0,  1);
```
Finally ,thank you for your repo!!
